/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardVendorsRouteImport } from './routes/dashboard.vendors'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as DashboardRfqsIndexRouteImport } from './routes/dashboard.rfqs.index'
import { Route as DashboardQuotationsIndexRouteImport } from './routes/dashboard.quotations.index'
import { Route as DashboardRfqsNewRouteImport } from './routes/dashboard.rfqs.new'
import { Route as DashboardQuotationsSubmitIdRouteImport } from './routes/dashboard.quotations.submit.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVendorsRoute = DashboardVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRfqsIndexRoute = DashboardRfqsIndexRouteImport.update({
  id: '/rfqs/',
  path: '/rfqs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotationsIndexRoute =
  DashboardQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRfqsNewRoute = DashboardRfqsNewRouteImport.update({
  id: '/rfqs/new',
  path: '/rfqs/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotationsSubmitIdRoute =
  DashboardQuotationsSubmitIdRouteImport.update({
    id: '/quotations/submit/$id',
    path: '/quotations/submit/$id',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/rfqs/new': typeof DashboardRfqsNewRoute
  '/dashboard/quotations/': typeof DashboardQuotationsIndexRoute
  '/dashboard/rfqs/': typeof DashboardRfqsIndexRoute
  '/dashboard/quotations/submit/$id': typeof DashboardQuotationsSubmitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/rfqs/new': typeof DashboardRfqsNewRoute
  '/dashboard/quotations': typeof DashboardQuotationsIndexRoute
  '/dashboard/rfqs': typeof DashboardRfqsIndexRoute
  '/dashboard/quotations/submit/$id': typeof DashboardQuotationsSubmitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/vendors': typeof DashboardVendorsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/rfqs/new': typeof DashboardRfqsNewRoute
  '/dashboard/quotations/': typeof DashboardQuotationsIndexRoute
  '/dashboard/rfqs/': typeof DashboardRfqsIndexRoute
  '/dashboard/quotations/submit/$id': typeof DashboardQuotationsSubmitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/activity'
    | '/dashboard/approvals'
    | '/dashboard/invoices'
    | '/dashboard/vendors'
    | '/dashboard/'
    | '/dashboard/rfqs/new'
    | '/dashboard/quotations/'
    | '/dashboard/rfqs/'
    | '/dashboard/quotations/submit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/activity'
    | '/dashboard/approvals'
    | '/dashboard/invoices'
    | '/dashboard/vendors'
    | '/dashboard'
    | '/dashboard/rfqs/new'
    | '/dashboard/quotations'
    | '/dashboard/rfqs'
    | '/dashboard/quotations/submit/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/signup'
    | '/dashboard/activity'
    | '/dashboard/approvals'
    | '/dashboard/invoices'
    | '/dashboard/vendors'
    | '/dashboard/'
    | '/dashboard/rfqs/new'
    | '/dashboard/quotations/'
    | '/dashboard/rfqs/'
    | '/dashboard/quotations/submit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/vendors': {
      id: '/dashboard/vendors'
      path: '/vendors'
      fullPath: '/dashboard/vendors'
      preLoaderRoute: typeof DashboardVendorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/rfqs/': {
      id: '/dashboard/rfqs/'
      path: '/rfqs'
      fullPath: '/dashboard/rfqs/'
      preLoaderRoute: typeof DashboardRfqsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotations/': {
      id: '/dashboard/quotations/'
      path: '/quotations'
      fullPath: '/dashboard/quotations/'
      preLoaderRoute: typeof DashboardQuotationsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rfqs/new': {
      id: '/dashboard/rfqs/new'
      path: '/rfqs/new'
      fullPath: '/dashboard/rfqs/new'
      preLoaderRoute: typeof DashboardRfqsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotations/submit/$id': {
      id: '/dashboard/quotations/submit/$id'
      path: '/quotations/submit/$id'
      fullPath: '/dashboard/quotations/submit/$id'
      preLoaderRoute: typeof DashboardQuotationsSubmitIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardVendorsRoute: typeof DashboardVendorsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardRfqsNewRoute: typeof DashboardRfqsNewRoute
  DashboardQuotationsIndexRoute: typeof DashboardQuotationsIndexRoute
  DashboardRfqsIndexRoute: typeof DashboardRfqsIndexRoute
  DashboardQuotationsSubmitIdRoute: typeof DashboardQuotationsSubmitIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardVendorsRoute: DashboardVendorsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardRfqsNewRoute: DashboardRfqsNewRoute,
  DashboardQuotationsIndexRoute: DashboardQuotationsIndexRoute,
  DashboardRfqsIndexRoute: DashboardRfqsIndexRoute,
  DashboardQuotationsSubmitIdRoute: DashboardQuotationsSubmitIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
